#  modes = ["rest_api", "forward_metrics"]
# Services configuration.
[[services]]
	name = "skycoin"
	modes = ["rest_api", "forward_metrics"]
	protocol = "http"
	port = 8000
	metricsToForwardPath = "/api/v1/metrics"
	authType = "CSRF"
	tokenHeaderKey = "X-CSRF-Token"
	genTokenEndpoint = "/api/v1/csrf"
	tokenKeyFromEndpoint = "csrf_token"

	[services.location]
		location = "localhost"


[[services]]
	name = "wallet"
	modes = ["rest_api", "forward_metrics"]
	protocol = "http"
	port = 8000
	metricsToForwardPath = "/api/metrics2"
	authType = "CSRF"
	tokenHeaderKey = "X-CSRF-Token"
	genTokenEndpoint = "/api/v1/csrf"
	tokenKeyFromEndpoint = "csrf_token"

	[services.location]
		location = "localhost"
