[[ResourcePaths]]
	Name = "connections"
	Path = "/api/v1/network/connections"
	PathType = "rest_api"
	nodeSolverType = "jsonPath"
	MetricNames = ["burnFactor"]

[[ResourcePaths]]
	Name = "health"
	Path = "/api/v1/health"
	PathType = "rest_api"
	nodeSolverType = "jsonPath"
	MetricNames = ["seq", "fee"]

[[ResourcePaths]]
	Name = "metricsFordwader"
	Path = "/api/v1/metrics"
	PathType = "metrics_fordwader"
	httpMethod = "GET"
