# All metrics to be measured.
[[metrics]]
	name = "burnFactor"
	path = "/connections/unconfirmed_verify_transaction/burn_factor"
	nodeSolver = "connections"

	[metrics.options]
		type = "Histogram"
		description = "Connections amount 1"

	[metrics.histogramOptions]
		buckets = [1, 2, 3]


[[metrics]]
	name = "seq"
	path = "/blockchain/head/seq"
	nodeSolver = "health"

	[metrics.options]
		type = "Counter"
		description = "I am running since"


[[metrics]]
	name = "fee"
	path = "/blockchain/head/fee"
	nodeSolver = "health"

	[metrics.options]
		type = "Counter"
		description = "I am running since"
