# All metrics to be measured.
[[metrics]]
	name = "burnFactor2"
	path = "/connections/unconfirmed_verify_transaction/burn_factor"
	nodeSolver = "connections"

	[metrics.options]
		type = "Histogram"
		description = "Connections amount 2"

	[metrics.histogramOptions]
		buckets = [0.5, 1.0, 2.0, 3.0, 5.0]
