[[ResourcePaths]]
	Name = "connections"
	Path = "/api/v1/network/connections"
	PathType = "rest_api"
	nodeSolverType = "jsonPath"
	MetricNames = ["burnFactor2"]

#[[ResourcePaths]]
#	Name = "metricsFordwader"
#	Path = "/metrics"
#	PathType = "forward_metrics"
#	nodeSolverType = "fordwader"
    
